name = "PhysicsInformedRegression"
uuid = "b39d95ae-da9c-4cd6-b0a9-f74eb13434aa"
authors = ["Marcus Galea Jacobsen", "Jonas Søeborg Nielsen", "Albert Brincker Olson"]
version = "1.0.1"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
DifferentialEquations = "^7"
ModelingToolkit = "^9"
Test = "<2.0.0"
LinearAlgebra = "<2.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
